#!/bin/sh -e

rootfs=$(df -m / |  awk '{ print $2 }' | tail -n1)
if [ $rootfs -lt 4096 ]; then
    echo "Expand disk..."
    parted --script /dev/mmcblk0 unit % resizepart 2 100%
    partprobe
    resize2fs /dev/mmcblk0p2
fi
